// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmfRdK6pImZMmztIPKGNhRt7bcR4DzzM',
    appId: '1:268994840057:web:38a041834b904cd0bfe928',
    messagingSenderId: '268994840057',
    projectId: 'bizitpos',
    authDomain: 'bizitpos.firebaseapp.com',
    storageBucket: 'bizitpos.appspot.com',
    measurementId: 'G-4F7VNQBJ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXQblrWICYCchUKYsVmMLLIh-u_Q9bTA',
    appId: '1:268994840057:android:04b0ba2e21ee6b9dbfe928',
    messagingSenderId: '268994840057',
    projectId: 'bizitpos',
    storageBucket: 'bizitpos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD83rIeFr2OlbUHqc2YGb_o58ekN7ssoCo',
    appId: '1:268994840057:ios:dd0efc03461f3ffbbfe928',
    messagingSenderId: '268994840057',
    projectId: 'bizitpos',
    storageBucket: 'bizitpos.appspot.com',
    iosBundleId: 'com.example.inventoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD83rIeFr2OlbUHqc2YGb_o58ekN7ssoCo',
    appId: '1:268994840057:ios:dd0efc03461f3ffbbfe928',
    messagingSenderId: '268994840057',
    projectId: 'bizitpos',
    storageBucket: 'bizitpos.appspot.com',
    iosBundleId: 'com.example.inventoryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxmfRdK6pImZMmztIPKGNhRt7bcR4DzzM',
    appId: '1:268994840057:web:64a365898dc2e77cbfe928',
    messagingSenderId: '268994840057',
    projectId: 'bizitpos',
    authDomain: 'bizitpos.firebaseapp.com',
    storageBucket: 'bizitpos.appspot.com',
    measurementId: 'G-8KPB6PK1CG',
  );
}
