name: inventoryapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  page_transition: ^2.1.0
  google_fonts: ^4.0.4
  http:
  fl_chart: ^0.67.0
  email_validator: ^2.1.17
  cupertino_icons: ^1.0.6
  excel: ^4.0.3
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_barcode_scanner: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
  country_picker: ^2.0.26
  uuid: ^4.4.0
  intl: ^0.19.0
  flutter_localization: ^0.2.0
  printing: ^5.12.0
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

flutter:

  uses-material-design: true

  assets:
    - lib/assets/Images/